name: Client

on:
  pull_request:
    branches:
      - main
    paths:
      - 'client/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint client
        run: npm run lint

      - name: Build client
        run: npm run build

      - name: Run client
        run: |
          PORT=3000 npm run preview &
          SERVER_PID=$!
          for i in {1..10}; do
            if curl -fs http://localhost:3000/; then
            echo "✅ Frontend is serving."
            break
          fi
          echo "⏳ Waiting for frontend..."
          sleep 1
          done
          kill $SERVER_PID
